/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// Wso2IsSpec defines the desired state of Wso2Is
type Wso2IsSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// Foo is an example field of Wso2Is. Edit Wso2Is_types.go to remove/update
	Size                int32  `json:"replicas"`
	ServiceType         string `json:"servicetype"`
	Configurations      string `json:"configurations"`
	ContainerImage      string `json:"containerimage"`
	InitialDelaySeconds int32  `json:"initialDelaySeconds"`
	PeriodSeconds       int32  `json:"periodSeconds"`
}

type AutoGenerated struct {
	Server     Server     `toml:"server"`
	SuperAdmin SuperAdmin `toml:"super_admin"`
	UserStore  UserStore  `toml:"user_store"`
	Database   Database   `toml:"database"`
	Keystore   Keystore   `toml:"keystore"`
}
type Server struct {
	Hostname string `toml:"hostname"`
	NodeIP   string `toml:"node_ip"`
}
type SuperAdmin struct {
	Username           string `toml:"username"`
	Password           string `toml:"password"`
	CreateAdminAccount bool   `toml:"create_admin_account"`
}
type UserStore struct {
	Type               string `toml:"type"`
	ConnectionURL      string `toml:"connection_url"`
	ConnectionName     string `toml:"connection_name"`
	ConnectionPassword string `toml:"connection_password"`
	BaseDn             string `toml:"base_dn"`
}
type IdentityDb struct {
	Type     string `toml:"type"`
	URL      string `toml:"url"`
	Username string `toml:"username"`
	Password string `toml:"password"`
}
type SharedDb struct {
	Type     string `toml:"type"`
	URL      string `toml:"url"`
	Username string `toml:"username"`
	Password string `toml:"password"`
}
type Database struct {
	IdentityDb IdentityDb `toml:"identity_db"`
	SharedDb   SharedDb   `toml:"shared_db"`
}
type Primary struct {
	FileName string `toml:"file_name"`
	Password string `toml:"password"`
}
type Keystore struct {
	Primary Primary `toml:"primary"`
}

// Wso2IsStatus defines the observed state of Wso2Is
type Wso2IsStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
	Nodes []string `json:"nodes"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// Wso2Is is the Schema for the wso2is API
type Wso2Is struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   Wso2IsSpec   `json:"spec,omitempty"`
	Status Wso2IsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// Wso2IsList contains a list of Wso2Is
type Wso2IsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Wso2Is `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Wso2Is{}, &Wso2IsList{})
}
