# permissions for end users to view userstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: userstore-viewer-role
rules:
- apiGroups:
  - wso2.wso2.com
  resources:
  - userstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wso2.wso2.com
  resources:
  - userstores/status
  verbs:
  - get
