apiVersion: wso2.wso2.com/v1
kind: Wso2Is
metadata:
  name: wso2is-operator
spec:
  replicas: 2

  configurations:
    server:
      hostname: $env{HOST_NAME}
      nodeIp:  $env{NODE_IP}
    superAdmin:
      username: admin
      password: admin
      createAdminAccount: true
    userStore:
      type: read_write_ldap_unique_id
      connectionUrl: ldap://localhost:${Ports.EmbeddedLDAP.LDAPServerPort}
      connectionName: uid=admin,ou=system
      connectionPassword: admin
      baseDn: dc=wso2,dc=org
    database:
      identityDb:
        type: h2
        url: jdbc:h2:./repository/database/WSO2IDENTITY_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
        username: wso2carbon
        password: wso2carbon
      sharedDb:
        type: h2
        url: jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
        username: wso2carbon
        password: wso2carbon
    keystore:
      primary:
        fileName: wso2carbon.jks
        password: wso2carbon