apiVersion: wso2.wso2.com/v1beta1
kind: Userstore
metadata:
  name: userstore-sample
spec:
  typeId: VW5pcXVlSURKREJDVXNlclN0b3JlTWFuYWdlcg
  description: Secondary userstore for identity server
  name: JDBS-SECONDARY
  properties:
    - name: connectionUrl
      value: jdbc://mysdsadasdsada
    - name: password
      value: 1234
